/** Tema organizacional y accesibilidad — seccion 4.3. */
export {
  checkContrast,
  contrastRatio,
  findContrastFailures,
  institutionalContrastChecks,
  parseHex,
  relativeLuminance,
  type ContrastCheck,
  type ContrastResult,
  type TextSize,
  type WcagLevel,
} from './contrast';
export { defaultIdentity, type InstitutionIdentity } from './identity';
export {
  OVERRIDABLE_TOKENS,
  defaultTheme,
  toCssVariables,
  validateOverrides,
  type ColorScale,
  type OverridableToken,
  type OverrideProblem,
  type ThemeOverrides,
  type ThemeTokens,
} from './tokens';
export {
  CONTRAST_PAIRS,
  CHART_PAIRS,
  SEMANTICA_POR_DEFECTO,
  schemeFor,
  palettesFor,
  type MaterialScheme,
  type ColorMode,
  type RoleTones,
  type ThemeSource,
  type TonalPalettes,
} from './material3';
export {
  ELEVATION,
  STATUS,
  SHAPE,
  OUTLINE_SCALES,
  OUTLINE_SCALE_NAMES,
  SHAPE_SCALES,
  SHAPE_SCALE_NAMES,
  SHADOW_SHAPES,
  SHADOW_SHAPE_NAMES,
  MOVIMIENTO,
  TINTE_NEUTRO,
  TYPOGRAPHY,
  TYPE_SCALES,
  TYPE_SCALE_NAMES,
  categoricalFor,
  elevationFor,
  materialTheme,
  materialVariables,
  tintOf,
  type Elevation,
  type OutlineScaleId,
  type ShadowShapeId,
  type ShapeScaleId,
  type ThemeStyle,
  type TypeScaleId,
  type TypographicStyle,
  type TypographicRole,
  type MaterialTheme,
} from './material3Tokens';
export {
  INSTITUTIONAL_SOURCE,
  INSTITUTIONAL_STYLE,
  FONTS,
  TYPEFACES,
  TYPEFACE_NAMES,
  type TypefaceId,
  asThemeTokens,
  lightTheme,
  darkTheme,
  themeForMode,
} from './institutionalTheme';
export {
  type ThemeDefinition,
  type SemanticRole,
  type SourceRole,
  BUILT_IN_THEMES,
  GRAPHIC_LINE_THEME,
  INSTITUTIONAL_THEME,
  SEMANTIC_ROLES,
  SOURCE_ROLES,
  sourceColorIs,
  themeStyle,
  themeVersion,
  themeVersions,
} from './themeDefinition';
