/** Repositorio de objetos visuales versionados — secciones 4.2 y 4.5. */
export { defaultSize, type DefaultSize, type SizeableObject } from './presentation/defaultSize';
export { ObjectRegistry, ObjectRegistryError, type DeprecationWarning, type PublishInput } from './registry/ObjectRegistry';
export {
  ATTACHMENT_BY_DEFAULT,
  ATTACHMENT_IDS,
  attachmentOf,
  filterableFields,
  validateAttachments,
  type AttachmentId,
  type SearchDefinition,
} from './registry/attachments';
export {
  applyVisualFilter,
  attachmentKeyIs,
  footerReferences,
  footerText,
  paginate,
  paginationKey,
  paginationLegend,
  visualFilterKey,
  type PaginationView,
} from './registry/attachmentView';
export { initialCatalog } from './registry/catalog';
export {
  COMPARATORS,
  MAX_RULES,
  conditionalColor,
  ruleDescribe,
  type Comparator,
  type ConditionalFormat,
  type ColorRule,
} from './presentation/conditional';
export {
  ACCENTS,
  AXIS_SCALES,
  FUNNEL_COMPARISONS,
  REFERENCE_STYLES,
  DATUM_POSITIONS,
  normalizedLabels,
  MAX_REFERENCES,
  CIRCULAR_LABELS,
  MAX_DECIMALS,
  MAX_RADIO_INTERIOR,
  MAX_SUBTITLE,
  MAX_UNIT,
  SORT_CRITERIA,
  STACKING_MODES,
  LEGEND_MODES,
  MIN_PRESENTATION,
  formatterOf,
  validatePresentation,
  type ObjectAccent,
  type PresentationKey,
  type NumericFormat,
  type FunnelComparison,
  type LabelSettings,
  type MultipleSettings,
  type TooltipSettings,
  type ReferenceStyle,
  type DatumLabels,
  type DatumPosition,
  type ReferenceLine,
  type PieSettings,
  type WaterfallSettings,
  type ComboSettings,
  type FunnelSettings,
  type AxisSettings,
  type AxisScale,
  type GaugeSettings,
  type HistogramSettings,
  type BoxplotSettings,
  type SortCriterion,
  type PieLabel,
  type StackingMode,
  type LegendMode,
  type CategorySort,
  type ObjectPresentation,
  type PresentationProblem,
} from './presentation/contract';
export {
  aFieldRef,
  bindingFromSlots,
  slotFits,
  slotField,
  withSlotField,
  slotsOf,
  contractSlots,
  defaultSlots,
  slotFieldWithout,
  validateSlots,
  type SlotAssignment,
  type FieldWell,
  type SlotProblem,
  type FieldSlot,
} from './presentation/wells';
export {
  PANEL_DIMENSIONS_MAX,
  DATE_PICKERS,
  FILTER_MODES,
  PICKER_KINDS,
  PICKER_LEVELS,
  VALUE_ORDERS,
  dateKindIs,
  defaultPicker,
  effectivePickers,
  modesByDefault,
  orderedValues,
  validatePanelFilters,
  type FiltersPanelSettings,
  type PickerProblem,
  type DimensionPicker,
  type SelectorEfectivo,
  type PickerKind,
  type PickerLevel,
  type FilterMode,
  type ValueOrder,
  type ValueCount,
} from './presentation/filtersPanel';
export {
  OBJECT_ICONS,
  ICON_NAMES,
  ICON_STROKES,
  iconNameIs,
  type IconName,
} from './presentation/icons';
export {
  DEFAULT_AGGREGATION,
  AGGREGATION_LABEL,
  acumular,
  aggregationsOf,
  aggregationsFor,
  possibleAggregations,
  close,
  newAccumulator,
  validateAggregation,
  type Accumulator,
  type AggregationContext,
  type AggregationProblem,
} from './registry/aggregation';
export {
  compareValues,
  buildMatrix,
  visibleRows,
  leaves,
  sortNodes,
  pathKey,
  type Direction,
  type HierarchicalMatrix,
  type MatrixNode,
} from './registry/matrix';
export {
  ALIGNMENTS,
  VERTICAL_ALIGNMENTS,
  TEXT_COLORS,
  TEXT_TARGETS,
  estiloDeTexto,
  type Alignment,
  type VerticalAlignment,
  type TextColor,
  type TextTarget,
  type TextStyle,
  type ObjectTexts,
} from './presentation/contract';
export {
  FORMAT_KINDS,
  measureFormat,
  numberFormatter,
  patternProblem,
  type NumberFormat,
  type ObjectFormats,
  type FormatKind,
} from './presentation/number';
export {
  PRESENTATION_KEYS,
  LABEL_POSITIONS,
  numberFormatAs,
  measureFormatter,
  type ValueLabel,
  type LabelPosition,
} from './presentation/contract';
export { breakdownOf, projectObject } from './registry/projection';
export {
  classifyBump,
  compareVersions,
  formatVersion,
  isValidVersion,
  maxVersion,
  parseVersion,
  type Semver,
  type VersionBump,
} from './registry/semver';
export { OBJECT_FAMILIES } from './registry/types';
export type {
  AttachedObjectInstance,
  AttachmentScope,
  DeprecationNotice,
  DrillThroughTarget,
  ObjectSettings,
  ObjectFamily,
  ObjectCategory,
  ObjectCertification,
  ObjectDataContract,
  ObjectInstance,
  ObjectVersion,
  TablePopupAttachment,
  TooltipAttachment,
  VisualFilterAttachment,
  FooterAttachment,
  PaginationAttachment,
  PaginationLegend,
  VisualObjectDefinition,
} from './registry/types';
export { PAGINATION_LEGENDS } from './registry/types';
export { notConsumesData, placeable } from './registry/types';
export {
  DEFAULT_CONNECTION,
  DEFAULT_BOX_TEXT,
  ELEMENTS,
  LINE_STYLES,
  ENDS,
  SHAPES,
  DEFAULT_SHAPE,
  DEFAULT_LINE_DIVIDER,
  ORIENTACIONES,
  LINE_POSITIONS,
  WITHOUT_CARD,
  DEFAULT_TITLE_SECTION,
  TRAZADOS,
  isElement,
  validThickness,
  lineStroke,
  type ConnectionSettings,
  type TextBoxSettings,
  type ElementSettings,
  type ShapeSettings,
  type LineSettings,
  type DividerLineSettings,
  type SectionTitleSettings,
  type LineStyle,
  type End,
  type Shape,
  type ElementId,
  type Orientation,
  type TextParagraph,
  type LinePosition,
  type Dash,
} from './presentation/elements';
export {
  DEFAULT_COLUMN_INTERNAL,
  DEFAULT_ROWS_ON_EXPAND,
  CONTAINERS,
  AXES,
  EMPTY_PANEL,
  columnsOf,
  rowsOnExpand,
  initialSettings,
  isContainer,
  nestedInstances,
  panelsOf,
  gridOverlapItself,
  validateContainer,
  type ContainerSettings,
  type ExpandableSettingsContainer,
  type ExpandableInPlaceSettings,
  type TabContainerSettings,
  type ScrollableSettingsContainer,
  type SimpleSettingsContainer,
  type Axis,
  type ContainerId,
  type NestedItem,
  type ContainerPanel,
  type PosicionEnRejilla,
  type ContainerProblem,
} from './presentation/containers';
export { trazar, type ObjectBox } from './presentation/connectors';
export {
  aggregateBy,
  fieldKey,
  toCategorical,
  toKpi,
  toMatrix,
  toSlicerOptions,
  validateBinding,
  type AggregatedRow,
  type AggregatedRows,
  type BindingProblem,
  type CategoricalViewModel,
  type CategoryPoint,
  type KpiViewModel,
  type MatrixViewModel,
} from './registry/viewModel';
export { sortCategories } from './charts/sort';
export {
  columnsFor,
  maxCommon,
  splitMultiples,
  type MultiplePanel,
} from './charts/multiples';
export {
  MAX_BINS,
  binLabel,
  binPosition,
  histogramOf,
  suggestedBins,
  type Bin,
  type Histogram,
} from './charts/histogram';
export {
  WHISKER_RULES,
  fiveNumberOf,
  numbersOf,
  quantile,
  type FiveNumber,
  type WhiskerRule,
} from './charts/statistics';
export { boxesOf, groupsOf, type Box } from './charts/boxplot';
export {
  ELEMENT_THRESHOLD,
  elementsOf,
  niceScale,
  gaugeScale,
  optionsOf,
  barOptions,
  pieOptions,
  lineOptions,
  gaugeOptions,
  histogramOptions,
  boxplotOptions,
  type ChartOptions,
  type ChartPalette,
  type ChartKind,
} from './charts/options';
export {
  BumpError,
  bumpInstance,
  isMajorJump,
  latestVersion,
  type BumpResult,
} from './registry/bump';
