/** Repositorio de objetos visuales versionados — secciones 4.2 y 4.5. */
export { ObjectRegistry, ObjectRegistryError, type DeprecationWarning, type PublishInput } from './registry/ObjectRegistry';
export {
  attachmentOf,
  validateAttachments,
  type BuscarDefinicion,
} from './registry/attachments';
export { catalogoInicial } from './registry/catalog';
export {
  COMPARADORES,
  MAX_REGLAS,
  colorCondicional,
  describirRegla,
  type Comparador,
  type ConditionalFormat,
  type ReglaDeColor,
} from './presentacion/condicional';
export {
  ACENTOS,
  COMPARACIONES_DE_EMBUDO,
  ESTILOS_DE_REFERENCIA,
  POSICIONES_DE_DATO,
  etiquetasNormalizadas,
  MAX_REFERENCIAS,
  ETIQUETAS_CIRCULARES,
  MAX_DECIMALES,
  MAX_RADIO_INTERIOR,
  MAX_SUBTITULO,
  MAX_UNIDAD,
  CRITERIOS_DE_ORDEN,
  MODOS_DE_APILADO,
  MODOS_DE_LEYENDA,
  PRESENTACION_MINIMA,
  formateadorDe,
  validarPresentacion,
  type AcentoDeObjeto,
  type ClaveDePresentacion,
  type FormatoNumerico,
  type FunnelComparison,
  type LabelSettings,
  type ConfiguracionDeMultiplos,
  type TooltipSettings,
  type ReferenceStyle,
  type DatumLabels,
  type PosicionDeDato,
  type ReferenceLine,
  type PieSettings,
  type WaterfallSettings,
  type ComboSettings,
  type FunnelSettings,
  type AxisSettings,
  type GaugeSettings,
  type CriterioDeOrden,
  type PieLabel,
  type StackingMode,
  type LegendMode,
  type OrdenDeCategorias,
  type PresentacionDeObjeto,
  type ProblemaDePresentacion,
} from './presentacion/contrato';
export {
  aFieldRef,
  bindingDesdeRanuras,
  cabeEnRanura,
  campoDeRanura,
  conCampoEnRanura,
  ranurasDe,
  ranurasDelContrato,
  ranurasPorDefecto,
  sinCampoEnRanura,
  validarRanuras,
  type AsignacionDeRanuras,
  type PozoDeCampos,
  type ProblemaDeRanura,
  type RanuraDeCampos,
} from './presentacion/pozos';
export {
  MAX_DIMENSIONES_DEL_PANEL,
  SELECTORES_DE_FECHA,
  TIPOS_DE_SELECTOR,
  esTipoDeFecha,
  selectorPorDefecto,
  selectoresEfectivos,
  validarPanelDeFiltros,
  type ConfiguracionDePanelDeFiltros,
  type ProblemaDeSelector,
  type SelectorDeDimension,
  type SelectorEfectivo,
  type TipoDeSelector,
} from './presentacion/panelDeFiltros';
export {
  ICONOS_DE_OBJETO,
  NOMBRES_DE_ICONO,
  TRAZOS_DE_ICONO,
  esNombreDeIcono,
  type NombreDeIcono,
} from './presentacion/iconos';
export {
  AGREGACION_POR_DEFECTO,
  ETIQUETA_DE_AGREGACION,
  acumular,
  agregacionesDe,
  agregacionesPara,
  agregacionesPosibles,
  cerrar,
  nuevoAcumulador,
  validarAgregacion,
  type Acumulador,
  type ContextoDeAgregacion,
  type ProblemaDeAgregacion,
} from './registry/agregacion';
export {
  compararValores,
  construirMatriz,
  filasVisibles,
  leaves,
  ordenarNodos,
  rutaClave,
  type Direccion,
  type MatrizJerarquica,
  type NodoDeMatriz,
} from './registry/matriz';
export {
  ALINEACIONES,
  ALINEACIONES_VERTICALES,
  COLORES_DE_TEXTO,
  DESTINOS_DE_TEXTO,
  estiloDeTexto,
  type Alineacion,
  type AlineacionVertical,
  type ColorDeTexto,
  type DestinoDeTexto,
  type EstiloDeTexto,
  type TextosDeObjeto,
} from './presentacion/contrato';
export {
  TIPOS_DE_FORMATO,
  formatoDeMedida,
  formateadorDeNumero,
  problemaDelPatron,
  type FormatoDeNumero,
  type FormatosDelObjeto,
  type TipoDeFormato,
} from './presentacion/numero';
export {
  CLAVES_DE_PRESENTACION,
  POSICIONES_DE_ETIQUETA,
  comoFormatoDeNumero,
  formateadorDeMedida,
  type EtiquetaDeValor,
  type PosicionDeEtiqueta,
} from './presentacion/contrato';
export { desgloseDe, proyectarObjeto } from './registry/proyeccion';
export {
  classifyBump,
  compareVersions,
  formatVersion,
  isValidVersion,
  maxVersion,
  parseVersion,
  type Semver,
  type VersionBump,
} from './registry/semver';
export { FAMILIAS_DE_OBJETO } from './registry/types';
export type {
  AttachedObjectInstance,
  AttachmentScope,
  DeprecationNotice,
  ConfiguracionDeObjeto,
  FamiliaDeObjeto,
  ObjectCategory,
  ObjectCertification,
  ObjectDataContract,
  ObjectInstance,
  ObjectVersion,
  TablePopupAttachment,
  TooltipAttachment,
  VisualObjectDefinition,
} from './registry/types';
export { noConsumeDatos } from './registry/types';
export {
  CONEXION_POR_DEFECTO,
  CUADRO_DE_TEXTO_POR_DEFECTO,
  ELEMENTOS,
  ESTILOS_DE_LINEA,
  EXTREMOS,
  FORMAS,
  FORMA_POR_DEFECTO,
  LINEA_DIVISORIA_POR_DEFECTO,
  ORIENTACIONES,
  POSICIONES_DE_LINEA,
  SIN_TARJETA,
  TITULO_DE_SECCION_POR_DEFECTO,
  TRAZADOS,
  esElemento,
  grosorValido,
  trazoDeLinea,
  type ConfiguracionDeConexion,
  type ConfiguracionDeCuadroDeTexto,
  type ConfiguracionDeElemento,
  type ConfiguracionDeForma,
  type ConfiguracionDeLinea,
  type ConfiguracionDeLineaDivisoria,
  type ConfiguracionDeTituloDeSeccion,
  type EstiloDeLinea,
  type Extremo,
  type Forma,
  type IdDeElemento,
  type Orientacion,
  type ParrafoDeTexto,
  type PosicionDeLinea,
  type Trazado,
} from './presentacion/elementos';
export {
  COLUMNAS_INTERNAS_POR_DEFECTO,
  CONTENEDORES,
  EJES,
  PANEL_VACIO,
  columnasDe,
  configuracionInicial,
  esContenedor,
  instanciasAnidadas,
  panelesDe,
  seSolapanEnRejilla,
  validarContenedor,
  type ContainerSettings,
  type ConfiguracionDeContenedorAmpliable,
  type ConfiguracionDeContenedorConPestanas,
  type ConfiguracionDeContenedorDesplazable,
  type ConfiguracionDeContenedorSimple,
  type Eje,
  type IdDeContenedor,
  type ItemAnidado,
  type PanelDeContenedor,
  type PosicionEnRejilla,
  type ProblemaDeContenedor,
} from './presentacion/contenedores';
export { trazar, type CajaDeObjeto } from './presentacion/conectores';
export {
  aggregateBy,
  fieldKey,
  toCategorical,
  toKpi,
  toMatrix,
  toSlicerOptions,
  validateBinding,
  type AggregatedRow,
  type AggregatedRows,
  type BindingProblem,
  type CategoricalViewModel,
  type CategoryPoint,
  type KpiViewModel,
  type MatrixViewModel,
} from './registry/viewModel';
export { sortCategories } from './charts/sort';
export {
  columnsFor,
  maxCommon,
  splitMultiples,
  type MultiplePanel,
} from './charts/multiples';
export {
  ELEMENT_THRESHOLD,
  elementsOf,
  niceScale,
  gaugeScale,
  optionsOf,
  barOptions,
  pieOptions,
  lineOptions,
  gaugeOptions,
  type ChartOptions,
  type ChartPalette,
  type ChartKind,
} from './charts/options';
